[workspace]
git_only = true
git_tag_enable = false
git_tag_name = "v{{ version }}"
git_release_enable = false
changelog_update = true
dependencies_update = false
semver_check = false
release_commits = "^(major|minor|patch): [^\\r\\n]*\\S[^\\r\\n]*(?:\\r?\\n|$)"
custom_minor_increment_regex = "^minor$"
custom_major_increment_regex = "^major$"
pr_name = "skip: prepare v{{ version }}"

[changelog]
protect_breaking_commits = false
commit_parsers = [
  { message = "^major: [^\\r\\n]*\\S[^\\r\\n]*(?:\\r?\\n|$)", group = "Major changes" },
  { message = "^minor: [^\\r\\n]*\\S[^\\r\\n]*(?:\\r?\\n|$)", group = "Minor changes" },
  { message = "^patch: [^\\r\\n]*\\S[^\\r\\n]*(?:\\r?\\n|$)", group = "Patch changes" },
  { message = "^feat[(:]", group = "Added" },
  { message = "^fix[(:]", group = "Fixed" },
  { message = "^perf[(:]", group = "Performance" },
  { message = "^skip: [^\\r\\n]*\\S[^\\r\\n]*(?:\\r?\\n|$)", skip = true },
  { message = ".*", group = "Other changes" },
]
