use std::ffi::OsStr;
use std::path::Path;

/// The tapas command catalog.
///
/// Tapas owns this catalog directly. It is no longer derived from the archived
/// smll project; new commands are added here together with their filter
/// implementation, fixtures, and regression cases (enforced by
/// `scripts/audit_catalog.py`).
pub const AUTO_WRAP_COMMANDS: &[&str] = &[
    "acli",
    "aws",
    "biome",
    "brew",
    "bun",
    "bunx",
    "cargo",
    "cat",
    "composer",
    "curl",
    "df",
    "docker",
    "docker-compose",
    "du",
    "eslint",
    "find",
    "gh",
    "git",
    "go",
    "gradle",
    "gradlew",
    "jest",
    "jq",
    "kubectl",
    "ls",
    "lsof",
    "make",
    "mocha",
    "mvn",
    "mvnw",
    "next",
    "ninja",
    "npm",
    "pnpm",
    "pre-commit",
    "ps",
    "psql",
    "pup",
    "pytest",
    "rg",
    "sqlite3",
    "systemctl",
    "terraform",
    "tofu",
    "tree",
    "tsc",
    "vitest",
    "webpack",
    "yarn",
    "zig",
];
pub const WRAPPER_COMMANDS: &[&str] = &[
    "acli",
    "aws",
    "bash",
    "biome",
    "brew",
    "bun",
    "bunx",
    "cargo",
    "cat",
    "composer",
    "curl",
    "df",
    "docker",
    "docker-compose",
    "dotnet",
    "du",
    "env",
    "eslint",
    "find",
    "gh",
    "git",
    "go",
    "gradle",
    "gradlew",
    "head",
    "jest",
    "jq",
    "kubectl",
    "ls",
    "lsof",
    "make",
    "mocha",
    "mvn",
    "mvnw",
    "mypy",
    "next",
    "ninja",
    "node",
    "npm",
    "pip",
    "pip3",
    "pnpm",
    "pre-commit",
    "prettier",
    "ps",
    "psql",
    "pup",
    "pytest",
    "rg",
    "ruff",
    "sh",
    "sqlite3",
    "swift",
    "systemctl",
    "tail",
    "terraform",
    "tofu",
    "tree",
    "tsc",
    "turbo",
    "uv",
    "uvx",
    "vitest",
    "wc",
    "webpack",
    "xcodebuild",
    "yarn",
    "zig",
    "zsh",
];
pub const GIT_SUBCOMMANDS: &[&str] = &[
    "add", "blame", "branch", "checkout", "commit", "config", "diff", "fetch", "grep", "log",
    "merge", "pull", "push", "remote", "rebase", "reflog", "shortlog", "show", "stash", "status",
    "switch", "tag", "worktree",
];
pub const PIPE_DETECTORS: &[&str] = &[
    "git_status",
    "git_branch",
    "git_reflog",
    "git_show",
    "GitDiffPipe",
    "GitLogCompact",
    "git_commit",
    "git_merge",
    "git_blame",
    "cargo_test",
    "jest",
    "js_test",
    "tsc",
    "go_test",
    "pytest",
    "kubectl_compact",
    "docker_compact",
    "npm_install",
    "tree",
    "ls_compact",
    "FindCompactPipe",
    "DuCompactPipe",
    "CurlCompactPipe",
    "GenericCompactPipe",
];
pub const TRANSPARENT_RUNNERS: &[&str] =
    &["bunx", "npx", "pnpm exec", "poetry run", "uv run", "uvx"];
pub const EXACT_OUTPUT_BYPASSES: &[&str] = &[
    "ambiguous_runner",
    "find_exact_output",
    "git_alternate_format",
    "lossless_or_raw",
    "ls_exact_output",
    "machine_output",
    "query",
    "tree_exact_output",
];
pub const STREAM_WATCH_POLICIES: &[&str] = &[
    "docker_compose_logs_follow",
    "docker_logs_follow",
    "gh_run_watch",
    "jest_watch",
    "journalctl_follow",
    "kubectl_logs_follow",
    "tail_follow",
    "tsc_watch",
    "unsupported_watch_inherit",
    "vitest_watch",
];

pub fn command_basename(command: &OsStr) -> Option<&OsStr> {
    Path::new(command).file_name()
}

pub fn should_auto_wrap(command: &OsStr) -> bool {
    let Some(basename) = command_basename(command) else {
        return false;
    };
    AUTO_WRAP_COMMANDS
        .iter()
        .any(|candidate| basename == OsStr::new(candidate))
}
